name: Build and Deploy to Amazon ECS

on:
  push:
    branches: [ main ]  # Trigger on main branch pushes

env:
  AWS_REGION: us-east-1
  ECR_REPO: demo-ecs
  CLUSTER_NAME: demo-ecs-cluster
  SERVICE_NAME: flask-ecs-task-defination-service-mi196uwf
  TASK_DEF: flask-ecs-task-defination.json
  CONTAINER_NAME: flask-container-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image to ECR
      id: build-image
      run: |
        IMAGE_TAG=latest-${GITHUB_SHA::7}
        ECR_IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:$IMAGE_TAG

        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        echo "ECR_IMAGE_URI=$ECR_IMAGE_URI" >> $GITHUB_ENV

        docker build -t $ECR_IMAGE_URI .
        docker push $ECR_IMAGE_URI

    - name: Fill in the new image URI in the task definition
      run: |
        sed "s|<IMAGE_PLACEHOLDER>|$ECR_IMAGE_URI|g" ${{ env.TASK_DEF }} > updated-task-def.json

    - name: Register new task definition
      id: register-task-def
      run: |
        TASK_DEF_ARN=$(aws ecs register-task-definition \
          --cli-input-json file://updated-task-def.json \
          --query "taskDefinition.taskDefinitionArn" --output text)
        echo "task-definition-arn=$TASK_DEF_ARN" >> $GITHUB_OUTPUT

    - name: Update ECS service to use new task definition
      run: |
        aws ecs update-service \
          --cluster ${{ env.CLUSTER_NAME }} \
          --service ${{ env.SERVICE_NAME }} \
          --task-definition ${{ steps.register-task-def.outputs.task-definition-arn }} \
          --force-new-deployment
